<<<<<<< HEAD
server:
  port: 8099
=======

>>>>>>> 6ff4a82f72e7f324976de3ecd6ec66662d253660
spring:
  profiles:
    active: a
  data:
    mongodb:
      host: localhost
      port: 27017
<<<<<<< HEAD
      database: bsj
      username: root
      password: Superzhouqi/15
      authentication-database: admin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
=======
      database: baisaiju

>>>>>>> 6ff4a82f72e7f324976de3ecd6ec66662d253660
